apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stash-volumesnapshot-demo
  labels:
    app: stash
rules:
- apiGroups:
  - stash.appscode.com
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stash-volumesnapshot-demo
  namespace: demo
  labels:
    app: stash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stash-volumesnapshot-demo
  namespace: demo
  labels:
    app: stash
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: stash-volumesnapshot-demo
subjects:
- kind: ServiceAccount
  name: stash-volumesnapshot-demo
  namespace: demo
