apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: db-volume-snapshot
spec:
  args:
    - backup
    - --namespace=${NAMESPACE:=default}
    - --shards=${shards}
    - --snapshot-class=${volumeSnapshotClass}
    - --output-dir=${outputDir:=}
  image: appscodeci/stash-volumesnapshot-demo:latest
